replicaCount: 2

image:
  repository: 390403890915.dkr.ecr.ap-south-1.amazonaws.com/ecom_order_ecr
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: ecomorder.ecomportal.com

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
secrets:
  database_password: "admin"

