trigger:
- main  # Change this if you want to trigger on another branch

variables:
  azureSubscription: 'ecom_resource_connection'  # Service connection name in Azure DevOps
  containerRegistry: 'ecomordercontainerregistry.azurecr.io'  # Azure Container Registry name
  containerRepository: 'ecomorder'  # Name of your app in ACR
  imageTag: '$(Build.BuildId)'  # Unique tag for each build
  resourceGroup: 'ecom_resource_group'  # Your Azure Resource Group
  containerAppName: 'ecomordercontainer'  # Your Azure Container App Name
  location: 'East Asia'  # Azure region

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push to ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: 'ecom_acr'  # Azure DevOps ACR service connection

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        command: buildAndPush
        repository: '$(containerRepository)'
        dockerfile: 'Dockerfile'
        containerRegistry: 'ecom_acr'
        tags: |
          $(imageTag)
          latest

- stage: Deploy
  displayName: 'Deploy to Azure Container Apps'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy Application'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Apps'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp update \
            --name $(containerAppName) \
            --resource-group $(resourceGroup) \
            --image $(containerRegistry)/$(containerRepository):$(imageTag) \
            --location $(location) \
            --query properties.configuration.ingress.fqdn
